A heap of changes to fix startup-to-GUI
This change replaces the network port mapping with network namespacing,
mainly because the Venus system depends on accessing the legacy GUI process
via port 81.

The Venusian now sets up a local bridged network and attaches the Venus
instance(s) to it. The network address is fixed to 192.168.42.0/24
(for now).

Also, there is a new setup option "--ext=IPADDR" which also attaches
the Venus instance to the given external IP address. Use "--ext=dyn" to
request an address via DHCP.

The web frontend now works, both in GUIv2 and GUIv1 mode, with the
caveats that (a) authorization is turned off (write an empty string
to /var/lib/venusian/conf/vncpassword.txt), (b) *not* using an
external address is untested.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -17,10 +17,8 @@ This script install The Venusian onto your computer, or a file system e.g. of a 
         If you use this option without "--install",
         a new user for your existing Venus installation will be created.
 
-    --vnc N
-        Use port 5900+N for VNC. The default is 1, or the next free port
-        as determined by the SCREEN=X entries in your /etc/venusian/*/vars
-        files.
+    --ext ADDR
+        Use this IP adress for the container. "dyn" uses DHCP.
 
     --fb
         Use the system's "real" video output.
@@ -118,6 +116,8 @@ test -s "$R/usr/bin/pstree" || I="$I psmisc"
 test -s "$R/usr/bin/sudo" || I="$I sudo"
 test -s "$R/usr/bin/make" || I="$I make"
 test -s "$R/usr/sbin/iptables" || I="$I iptables"
+test -s "$R/usr/sbin/jq" || I="$I jq"
+test -s "$R/usr/sbin/nc.openbsd" || I="$I netcat-openbsd"
 test -s "$R/usr/bin/socat" || I="$I socat"
 test -s "$R/usr/bin/bluetoothctl" || I="$I bluez"
 test -s "$R/usr/bin/fuse-overlayfs" || I="$I fuse-overlayfs"
@@ -199,7 +199,7 @@ fln() {
 }
 
 
-next_vnc() {
+next_screen() {
     # well, "next" unless it's an existing user who already has a screen#
     if [ ! -d /etc/venusian ] ; then
         echo 1
@@ -239,10 +239,11 @@ mkdir -p "$R/$SC/default.target.wants/"
 fln "$SERVICE" "$R/$LIBV/.config/systemd/user"
 fln ".config/systemd/user.control" "$R/$LIBV/service"
 
-[ -v HTTP ] || HTTP=$(( 58000 + $SCREEN ))
 fcat "$R/$LIBV/nginx-fwd.conf" <<_END_
+# XXX TODO this is broken when using native networking
+#
 location /$NAME/ {
-        proxy_pass http://127.0.0.1:$HTTP/;
+        proxy_pass http://192.168.42.$SCREEN:80/;
         proxy_set_header Host \$host;
         proxy_set_header X-Real-IP \$remote_addr;
         proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
@@ -265,6 +266,7 @@ mkdir -p "$R$LIBV/"{conf,db,log,etc,themes,var/lib}
 
 USERID=$(grep "^$NAME:" $R/etc/passwd | ( IFS=: read a b c d ; echo $c ) )
 env USER=$NAME UID=$USERID $USRV/bin/get-unique-id > $R$LIBV/conf/unique-id
+cp $R$LIBV/conf/unique-id $R$LIBV/venus/unique-id
 
 chroot "$R" chown -R $NAME $LIBV/{etc,conf,db,log,.config}
 
@@ -275,23 +277,145 @@ if test ! -s "$VPW" ; then
     pwd=
 fi
 
-mkdir -p "$R/$UD"
 mkdir -p "$R/$EV"
 
-fcat "$R/$UD/venusian.conf" <<_END_
+## Networking.
+
+# Step 1: a bridged network interface for Venusian.
+
+fcat "$R/etc/systemd/system/venusian-net.service" <<_END_
 [Unit]
+Description=Optional bridge interface for Venusian
+
+[Service]
+Type=oneshot
+RemainAfterExit=yes
+
+EnvironmentFile=-/etc/venusian/vars
+
+ExecStart=/usr/lib/venusian/bin/setup-netif
+ExecStop=-ip link del dev venusian
+ExecStop=sleep 3
+# due to Avahi nonsense
+_END_
+
+# Step 1a: tell systemd-networkd to ignore new bridged nodes
+#
+fcat "$R/etc/systemd/network/00-venusian-any.network" <<_END_
+[Match]
+Name=venusian-*
+
+[Network]
+Unmanaged=yes
+RequiredForOnline=no
+_END_
+
+# Step 1b: tell systemd-networkd to handle the bridge
+#
+fcat "$R/etc/systemd/network/00-venusian.network" <<_END_
+[Match]
+Name=venusian
+
+[Network]
+Description=Venusian network bridge
+RequiredForOnline=no
+DHCPServer=no
+
+LinkLocalAddressing=no
+LLMNR=no
+LLDP=no
+EmitLLDP=no
+
+Address=192.168.42.254/24
+
+#[DHCPServer]
+#PoolOffset=130
+#PoolSize=120
+_END_
+
+# Step 2: create a per-user network namespace
+fcat "$R/etc/systemd/system/venusian-netns@.service" <<_END_
+[Unit]
+Description=Network namespace for Venusian %i
+StopWhenUnneeded=true
+Requires=venusian-net.service
+After=venusian-net.service
+
+[Service]
+Type=oneshot
+RemainAfterExit=yes
+#PrivateNetwork=yes
+
+EnvironmentFile=-/etc/venusian/vars
+EnvironmentFile=-$EV/vars
+
+# Ask ip netns to create a named network namespace
+# (This ensures that things like /run/netns are properly setup)
+ExecStart=/usr/lib/venusian/bin/setup-netspace %i
+
+# Clean up
+ExecStop=ip netns delete venusian-%i
+_END_
+
+# Step 3: Run the user.
+#
+fcat "$R/etc/systemd/system/venusian@.service" <<_END_
+[Unit]
+Description=Venusian Manager for UID %i
+BindsTo=user-runtime-dir@%i.service
+After=systemd-logind.service user-runtime-dir@%i.service dbus.service systemd-oomd.service
+
+After=venusian-netns@%i.service
+Requires=venusian-netns@%i.service
+
 After=opt-victronenergy.mount $MNT_U
 Requires=opt-victronenergy.mount $MNT_U
 
 [Service]
+User=%i
+PAMName=systemd-user
+Type=notify-reload
+PrivateMounts=yes
+ExecStartPre=-/usr/lib/venusian/bin/setup-user %i
+ExecStart=/usr/lib/systemd/systemd --user
+Slice=user-%i.slice
+# Reexecute the manager on service reload, instead of reloading.
+# This provides a synchronous method for restarting all user manager
+# instances after upgrade.
+ReloadSignal=RTMIN+25
+KillMode=mixed
+Delegate=pids memory cpu
+DelegateSubgroup=init.scope
+TasksMax=infinity
+TimeoutStopSec=120s
+KeyringMode=inherit
+OOMScoreAdjust=100
+MemoryPressureWatch=skip
+
+NetworkNamespacePath=/run/netns/venusian-%i
+AmbientCapabilities=CAP_NET_BIND_SERVICE
+#AmbientCapabilities=CAP_NET_ADMIN
+
 BindPaths=/var/lib/venusian/%i:/data
 BindPaths=/var/lib/venusian/%i/etc:/etc/venus
 
 EnvironmentFile=-/etc/venusian/vars
 EnvironmentFile=-$EV/vars
+#Environment=XDG_RUNTIME_DIR=/run/venusian/%i
 
-ExecStartPost=+$USRV/bin/iptables-redirect on
-ExecStopPost=+$USRV/bin/iptables-redirect off
+ExecStartPre=+mkdir -p /run/venusian/%i
+ExecStartPre=+chown %i /run/venusian/%i
+#ExecStartPost=+$USRV/bin/iptables-redirect on
+#ExecStopPost=+$USRV/bin/iptables-redirect off
+_END_
+
+# Venus service (shortcut)
+fcat "$R/etc/systemd/system/venus.target" <<_END_
+[Unit]
+Requires=venusian@venus.service
+
+[Install]
+RequiredBy=multi-user.target
 _END_
 
 if [ ! -s "$R/$EV/vars" ] || ! grep -qs "^SCREEN=" "$R/$EV/vars" ; then
@@ -300,13 +424,16 @@ fi
 if [ -v FB ] ; then
     echo FB=y >>"$R/$EV/vars"
 fi
+if [ -v EXT ] ; then
+    echo "EXT='$ext'" >>"$R/$EV/vars"
+fi
 
 subs user
 } # END gen_user
 
 
 # command line processing
-TEMP=$(getopt -o 'fFi:Id:hm:nqr:Rs:u:v?' --long 'dest:,fast,fb,force,help,image:,install,mount:,no-update,replace,repo:,repo-key:,root:,skip,sub:,user:,verbose' -n "$0" -- "$@")
+TEMP=$(getopt -o 'fFi:Id:hm:nqr:Rs:u:v?' --long 'dest:,ext:,fast,fb,force,help,image:,install,mount:,no-update,replace,repo:,repo-key:,root:,skip,sub:,user:,verbose' -n "$0" -- "$@")
 if [ $? -ne 0 ]; then
     usage >&2
 fi
@@ -324,7 +451,7 @@ SUB_UPD=y
 REPO=http://build.smurf.noris.de/info/smurf.list
 REPOKEY=http://build.smurf.noris.de/info/smurf.archive.gpg
 replace=
-unset NAME DEST MNT img fast FB INST
+unset NAME DEST MNT img fast FB INST EXT
 
 while : ; do
     case "$1" in
@@ -334,6 +461,9 @@ while : ; do
         (-q|--quiet)
             Q=":"
             shift ;;
+        (--ext)
+            EXT="$2"
+            shift 2;;
         (-f|--force)
             FORCE=y
             shift ;;
@@ -442,10 +572,9 @@ else
     NAME=venus
 fi
 
-SCREEN=$(next_vnc $NAME)
+SCREEN=$(next_screen $NAME)
 MNT_U=$(systemd-escape -m "$MNT")
 
-UD="/etc/systemd/system/user@$NAME.service.d/"
 EV="/etc/venusian/$NAME"
 
 if test "$verb" = "y" ; then
@@ -466,6 +595,7 @@ if [ -d "$USRV" ]; then
         echo -n "$u "
     done
     echo "."
+    systemctl stop venusian-net || true
     umount /opt/victronenergy || true
     umount /opt/venus || true
     rm -r "$USRV"
@@ -724,6 +854,7 @@ fln "$MNT/usr/lib/fonts" "$R/usr/lib/fonts"
 fln "$MNT/usr/lib/gconv" "$R/usr/lib/gconv"
 
 fln "$MNT/var/www/venus" "$R/var/www/venus"
+fln "$MNT/var/www/venus/index.php" "$R/data/www/venus"
 
 # if /o/v is a mountpoint, assume that it's our overlay,
 # thus we write to that. Otherwise we write to the overlay's
@@ -775,10 +906,11 @@ starters | while read f ; do
         (nginx)
             # TODO investigate using the global nginx server directly
             echo >>$U ExecStartPre=$USRV/bin/gen-nginx-conf
-            echo >>$U ExecStart=/usr/sbin/nginx -c /run/user/%U/nginx.conf
-            echo >>$U ExecReload=/usr/sbin/nginx -c /run/user/%U/nginx.conf -s reload
+            echo >>$U ExecStart=nginx -c /run/user/%U/nginx.conf
+            echo >>$U ExecReload=nginx -c /run/user/%U/nginx.conf -s reload
             echo >>$U TimeoutStopSec=5
             echo >>$U KillMode=mixed
+	    echo >>$U AmbientCapabilities=CAP_NET_BIND_SERVICE
             ;;
         (serial-starter) # that's the job of our udev-handler
             fln "$SERVICE/udev-handler.service" "$WANTS/udev-handler.service"
@@ -799,6 +931,7 @@ starters | while read f ; do
         (gui)
             echo >>$U WorkingDirectory="/opt/victronenergy/gui"
             echo >>$U ExecStart="$USRV/bin/start-gui"
+            echo >>$U AmbientCapabilities=CAP_NET_BIND_SERVICE
             ;;
         (ssh-tunnel) ;; # no remote access via some tunnel
         (vrmlogger) ;; # no external logging
@@ -809,14 +942,19 @@ starters | while read f ; do
                 exit 1
             fi
             echo >>$U ExecStartPre=$USRV/bin/gen-phpfpm-conf
-            echo >>$U ExecStart=/usr/sbin/php-fpm$V -y /run/user/%U/phpfpm.conf
+            echo >>$U ExecStart=php-fpm$V -y /run/user/%U/phpfpm.conf
             ;;
         (*)
-	        if grep -qs etc.profile.d $MNT/opt/victronenergy/service/$fx/run ; then
-                mkdir -p $OPTVIC/service/$fx
-                sed -e /etc.profile.d/d <$MNT//opt/victronenergy/service/$fx/run | fcat $OPTVIC/service/$fx/run
-            fi
-            echo >>$U ExecStart=/opt/victronenergy/service/$fx/run
+            mkdir -p $OPTVIC/service/$fx
+            (
+			    cat <<_
+#!/bin/bash
+BASH_ARGV0="$fx"
+
+_
+                sed -e '/^#!.bin.sh/d' -e /etc.profile.d/d -e '/^exec 2>&1$/d' <$MNT//opt/victronenergy/service/$fx/run
+            ) | fcat $OPTVIC/service/$fx/run
+            echo >>$U ExecStart=/opt/victronenergy/service/$fx/run "%N"
             ;;
     esac
     echo >>$U "Type=simple"
@@ -1051,6 +1189,6 @@ gen_user $NAME
 
 subs post
 
-test "$R" = "/" && systemctl daemon-reload
+test "$R" = "/" && systemctl daemon-reload && systemctl reload systemd-networkd
 
 $Q echo "Done."
